config/routes.rb
Rails.application.routes.draw do
  resources :currency_converts
  resources :currencies
  get 'time', to: 'currency_converts#time' 
  get 'convert', to: 'currency_converts#convert'    
  root to: "currencies#index"

end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/currency_convert.rb
class CurrencyConvert < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController 
  before_action :set_currency, only: [:show, :edit, :update, :destroy]
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
    @array = []
    get_currency
  end


  def get_currency
    @currencies.each do |currency| 
      @data = YahooFinance::Client.new.quotes(["BVSP", "NATU3.SA", currency.currency + currency.currency_to + "=X"], [:ask, :change, :weeks_range_52, :last_trade_price])
      @array.push(@data)
    end
  end
  # GET /currencies/1
  # GET /currencies/1.json
  
  def show

  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end
  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end 
    end
  end

  def data
    @data
  end
  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:currency, :currency_to)
    end
end

app/controllers/currency_converts_controller.rb
class CurrencyConvertsController < ApplicationController
  before_action :set_currency_convert, only: [:show, :edit, :update, :destroy]

  def index
    @currency_converts = Currency.all
    @array = []
  end

  def convert
    @i = params[:q][:number].to_i   
    currency_converts = Currency.all
    data = YahooFinance::Client.new.quotes(["BVSP", "NATU3.SA", currency_converts[@i].currency + currency_converts[@i].currency_to + "=X"], [:ask])
    @sum = params[:q][:index]
    @data = data[2].ask
    respond_to do |format|
      format.js
    end 
  end

  def new
    @currency_convert = Currency.new
  end

  def time
    @text = Time.now.to_s
   respond_to do |format|
    format.js
   end
  end

  def show 
  end

  def create
    @currency_convert = Currency.new(currency_convert_params)

    respond_to do |format|
      if @currency_convert.save
        format.html { redirect_to @currency_convert, notice: 'Currency convert was successfully created.' }
        format.json { render :show, status: :created, location: @currency_convert }
      else
        format.html { render :new }
        format.json { render json: @currency_convert.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @currency_convert.update(currency_convert_params)
        format.html { redirect_to @currency_convert, notice: 'Currency convert was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency_convert }
      else
        format.html { render :edit }
        format.json { render json: @currency_convert.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @currency_convert.destroy
    respond_to do |format|
      format.html { redirect_to currency_converts_url, notice: 'Currency convert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency_convert
      @currency_convert = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_convert_params
      params.require(:currency_convert).permit(:currency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/currency_converts_helper.rb
module CurrencyConvertsHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :currency_to %><br>
    <%= f.text_field :currency_to %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>
<%= render 'form' %>
<%= link_to 'Show', @currency %> 
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<p id="notice"><%= notice %></p>

<div id="infoArea" style="display: @none">
  <div class="marketHead">
    <h1 class="shiftedShadow">Курсы наличных валют</h1>
    <h3> <%= link_to 'Добавить валюту', new_currency_path %></h3>
  </div>
</div>

<table id="marketRates" class="keTable">
  <thead class="green2 textLinkShadow">
    <tr>
      <th>Валюта</th>
      <th title="Средний курс покупки">Продажа, руб</th>
      <th title="Средний курс покупки">Покупка, руб</th>
      <th title="Изменения за год">Изменения за год, руб</th>
      <th title="Настройки">Настройки</th>
    </tr>
  </thead>
  
  <% a = 0 %>
  <% @currencies.each do |currency| %>
    <tr>
      <td class="curr textLinkShadow"><%= currency.currency %>/<%= currency.currency_to %></td>
      <td>
        <%= @array[a][2].ask %><sup class="increased" title="Изменение за сутки"><%= @array[a][2].change %></sup>
      </td>
      <td><%=@array[a][2].last_trade_price %></td>
      <td><%= @array[a][2].weeks_range_52 %></td>
      <td>  
        <%= link_to 'Edit', edit_currency_path(currency) %>
        <%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <%  a = a + 1%>
  <% end %>
</table>

app/views/currencies/new.html.erb
<h1>New Currency</h1>
<%= render 'form' %>
<%= link_to 'Show', @currency %> 
<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Currency:</strong>
  <%= @currency.currency %>
</p>

<p>
  <strong>Currency to:</strong>
  <%= @currency.currency_to %>
</p>

<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>

app/views/currency_converts/_form.html.erb
<%= form_for(@currency_convert) do |f| %>
  <% if @currency_convert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency_convert.errors.count, "error") %> prohibited this currency_convert from being saved:</h2>

      <ul>
      <% @currency_convert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
    <br>
    <%= f.label :currency_to %><br>
    <%= f.text_field :currency_to %>
    
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currency_converts/convert.js.erb
result = <%= @sum %> * <%= @data %>
$(".result" + <%= @i %>).empty().append(result.toFixed(2))
result = <%= @sum %> / <%= @data %>
$(".result2" + <%= @i %>).empty().append(result.toFixed(2))

app/views/currency_converts/edit.html.erb
<h1>Editing Currency Convert</h1>
<%= render 'form' %>
<%= link_to 'Show', @currency_convert %> |
<%= link_to 'Back', currency_converts_path %>

app/views/currency_converts/index.html.erb
<p id="notice"><%= notice %></p>

<div id="infoArea" style="display: @none">
  <div class="marketHead">
    <h1 class="shiftedShadow">Конвертер валют</h1>
    <h3> <%= link_to 'Новая валюта для конвертации', new_currency_convert_path %></h3>
  </div>
</div>
    
<table id="marketRates" class="keTable">
  
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>
  
  <thead class="green2 textLinkShadow">    
    <tr>
        <th>Валюта</th>
        <th title="Сумма">Сумма для конвертации</th>
        <th title="Результат">Результат</th>
        <th title="Результат">Результат2</th>
        <th title="Настройки">Настройки</th>

    </tr>
  </thead>
  
  <%= link_to "time", time_path, remote: true %>
  <div id='time_div'></div>

  <% index = 0%>
  <% @currency_converts.each do |currency_convert| %>
    <tr>
    <td class="curr textLinkShadow"><%= currency_convert.currency %> => <%= currency_convert.currency_to %></td>
    
    <td>
        <%= form_for :q, url: {action: 'convert'}, method: :get, remote: true  do |f| %>
          <%= f.number_field :index %>
          <%= f.hidden_field :number, value: index %>
          <%= f.submit ("convert") %>
        <% end %>
    </td>

    <td>
      <%= currency_convert.currency %> => <%= currency_convert.currency_to %>
      <div class="green2 textLinkShadow">
      <%= content_tag :div, class: "result#{index}" do %><% end %>
      </div>
    </td>

    <td> 
      <%= currency_convert.currency_to %> => <%= currency_convert.currency %>
      <div class="green2 textLinkShadow">
      <%= content_tag :div, class: "result2#{index}" do %><% end %>
      </div>
    </td>
  
    <td>
      <%=link_to 'Edit', edit_currency_convert_path(currency_convert)%> <%= link_to 'Destroy', currency_convert, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
    </tr>
    <% index += 1 %>
  <% end %>
</table>

app/views/currency_converts/new.html.erb
<h1>New Currency Convert</h1>
<%= render 'form' %>
<%= link_to 'Back', currency_converts_path %>

app/views/currency_converts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Currency:</strong>
  <%= @currency_convert.currency %>
  <%= @currency_convert.currency_to %>

</p>

<%= link_to 'Edit', edit_currency_convert_path(@currency_convert) %> |
<%= link_to 'Back', currency_converts_path %>

app/views/currency_converts/time.js.erb
$('#time_div').empty().append("<%= @text %>")

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html ng-app>
<head>
    <meta charset="UTF-8">
    <title>Курсы наличных валют — Анализатор Валют</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>   
</head>
<body>
<div id="container">

  <div id="content">
      <header>
      <div id="topArea" class="topShadow">
          <ul class="topmenu menuStyle" style="display: @none">
              <a href="currencies">
                  <li>Главная</li>
              </a>
              <a href="currency_converts">
                  <li>Конвертер</li>
              </a>
          </ul>
      </div>
  </div>
  </header>
<body>

<%= yield %>

</body>
</html>